default:
  image: docker:19.03.08
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["docker-entrypoint.sh"]

stages:
  - build-jar
  - test-image
  - push-image
  - test-jar
  - build-docker-image
  - release
  - deploy

build-jar: